const API={python:'/api'};
const CONFIG={brand:'SR BRAND',topbar:'✨ Livraison gratuite partout au Maroc · Commandez maintenant',email:'anassnaoui146@gmail.com',whatsapp:'+212 727-951624',whatsappDisplay:'+212 727-951624',address:'Votre ville, Maroc',instagram:'@yourbrand',instagramUrl:'https://instagram.com/yourbrand'};
const LOCAL_PRODUCTS=[{id:1,name:'Ensemble Premium',category:'ensembles',price:299,badge:'BEST SELLER',image: "static/images/collections/collection-01.png",description:'Décrivez ici votre collection.',sizes:['S','M','L','XL']},{id:2,name:'Robe Signature',category:'robes',price:249,oldPrice:399,badge:'NOUVEAU',image:'static/images/collections/scott-womens-knickers-endurance-10-pantalon-de-cyclisme.png',description:'Ajoutez votre description de collection.',sizes:['S','M','L']},{id:3,name:'Ensemble Satin',category:'ensembles',price:319,oldPrice:450,badge:'-29%',image:'static/images/collections/soutien-pimenton-elena-blanco.png',description:'Ajoutez votre description de collection.',sizes:['S','M','L','XL']},{id:4,name:'Sac Minimal',category:'accessoires',price:179,oldPrice:229,badge:'ÉDITION',image:'static/images/collections/images.png',Image:'static/images/collections/IMG_9198-scaled.png',description:'Ajoutez votre description de collection.',sizes:['Unique']}];
let PRODUCTS=[...LOCAL_PRODUCTS],cart=JSON.parse(localStorage.getItem('yourbrand_cart')||'[]'),activeCategory='all',searchTerm='';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function applyConfig(){document.title=document.title.replace('YOUR BRAND',CONFIG.brand);$$('#brandLogo,.footer-logo,#footerBrand').forEach(e=>e.textContent=CONFIG.brand);const t=$('#topbarText');if(t)t.textContent=CONFIG.topbar;const em=$('#contactEmail,#footerEmail');$$('#contactEmail,#footerEmail').forEach(e=>{e.textContent=CONFIG.email;if(e.tagName==='A')e.href=`mailto:${CONFIG.email}`});$$('#contactWhatsapp').forEach(e=>{e.textContent=CONFIG.whatsappDisplay;e.href=`https://wa.me/${CONFIG.whatsapp}`});const fw=$('#footerWhatsapp');if(fw)fw.textContent=CONFIG.whatsappDisplay;const ad=$('#contactAddress,#footerAddress');$$('#contactAddress,#footerAddress').forEach(e=>e.textContent=CONFIG.address);const ig=$('#instagramLink');if(ig){ig.textContent=CONFIG.instagram;ig.href=CONFIG.instagramUrl}const y=$('#year');if(y)y.textContent=new Date().getFullYear();}
function setActiveNav(){const p=location.pathname.split('/').pop()||'index.html';const key=p==='index.html'?'accueil':p.replace('.html','');const a=document.querySelector(`[data-nav="${key}"]`);if(a)a.classList.add('active');}
function initMobile(){const b=$('#mobileMenuBtn'),n=$('#mainNav');if(b&&n)b.addEventListener('click',()=>n.classList.toggle('open'));}
async function loadProducts(){try{const r=await fetch(`${API.python}/products`);if(!r.ok)throw 0;const data=await r.json();if(Array.isArray(data)&&data.length)PRODUCTS=data}catch(e){console.warn('API unavailable; local fallback')} }
function productCard(p){return `<article class="product-card"><div class="product-media"><span class="label">${p.badge||p.category.toUpperCase()}</span><div class="product-image-placeholder" ${p.image?`style="background-image:url('${p.image}');background-size:cover;background-position:center"`:''}>${p.image?'':`IMAGE PRODUIT ${String(p.id).padStart(2,'0')}`}</div><div class="product-actions"><button class="quick-btn" data-quick="${p.id}">⌕</button><button class="quick-btn" data-add="${p.id}">＋</button></div></div><div class="product-info"><h3>${p.name}</h3><div><span class="price">${Number(p.price).toFixed(0)} DH</span>${p.oldPrice?`<span class="old-price">${Number(p.oldPrice).toFixed(0)} DH</span>`:''}</div></div></article>`;}
function renderProducts(target='#productGrid',featured=false){const grid=$(target);if(!grid)return;let arr=PRODUCTS.filter(p=>(activeCategory==='all'||p.category===activeCategory)&&p.name.toLowerCase().includes(searchTerm.toLowerCase()));if(featured)arr=arr.slice(0,4);grid.innerHTML=arr.length?arr.map(productCard).join(''):'<div style="grid-column:1/-1;padding:50px;text-align:center">Aucun produit trouvé.</div>';$$('[data-quick]').forEach(b=>b.onclick=()=>openProduct(+b.dataset.quick));$$('[data-add]').forEach(b=>b.onclick=()=>addToCart(+b.dataset.add));}
function openProduct(id){const p=PRODUCTS.find(x=>x.id===id),m=$('#productModal'),c=$('#modalContent');if(!p||!m||!c)return;c.innerHTML=`<div class="modal-product"><div class="modal-media">${p.image?`<img src="${p.image}" alt="${p.name}" style="width:100%;height:100%;object-fit:cover;border-radius:20px">`:`IMAGE PRODUIT ${p.id}`}</div><div class="modal-copy"><p class="eyebrow">${p.badge||'COLLECTION'}</p><h2>${p.name}</h2><div class="price">${p.price} DH</div><p>${p.description||''}</p><div class="size-grid">${(p.sizes||[]).map((s,i)=>`<button class="${i===0?'active':''}">${s}</button>`).join('')}</div><button class="button button-dark" id="modalAdd">Ajouter au panier</button></div></div>`;m.classList.add('show');$('#modalAdd').onclick=()=>{addToCart(p.id);m.classList.remove('show')}}
function addToCart(id){const p=PRODUCTS.find(x=>x.id===id),e=cart.find(x=>x.id===id);if(!p)return;if(e)e.qty++;else cart.push({id,qty:1});localStorage.setItem('yourbrand_cart',JSON.stringify(cart));renderCartCount();showToast('Produit ajouté au panier');}
function renderCartCount(){const n=$('#cartCount');if(n)n.textContent=cart.reduce((s,x)=>s+x.qty,0);}
function renderCartPage(){const box=$('#cartItemsPage'),totalEl=$('#cartTotalPage');if(!box)return;let total=0;if(!cart.length){box.innerHTML='<div style="padding:50px;text-align:center">Votre panier est vide.<br><a class="button button-dark" href="boutique.html" style="margin-top:20px;display:inline-block">Retour à la boutique</a></div>';if(totalEl)totalEl.textContent='0 DH';return}box.innerHTML=cart.map(i=>{const p=PRODUCTS.find(x=>x.id===i.id);const line=p.price*i.qty;total+=line;return `<div class="cart-page-line"><div class="cart-thumb">${p.image?`<img src="${p.image}" alt="">`:''}</div><div><h3>${p.name}</h3><p>${p.price} DH</p><div class="qty"><button data-minus="${i.id}">−</button><span>${i.qty}</span><button data-plus="${i.id}">+</button></div></div><strong>${line} DH</strong></div>`}).join('');if(totalEl)totalEl.textContent=`${total} DH`;$$('[data-minus]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.minus,-1));$$('[data-plus]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.plus,1));}
function changeQty(id,d){const i=cart.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty<=0)cart=cart.filter(x=>x.id!==id);localStorage.setItem('yourbrand_cart',JSON.stringify(cart));renderCartCount();renderCartPage();}
function checkout(){if(!cart.length)return showToast('Votre panier est vide');const n=prompt('Votre nom complet :');if(!n)return;const ph=prompt('Votre téléphone :');if(!ph)return;const ad=prompt('Votre adresse :');if(!ad)return;let total=0;const lines=cart.map(i=>{const p=PRODUCTS.find(x=>x.id===i.id);const lineTotal=p.price*i.qty;total+=lineTotal;return `- ${p.name} x${i.qty} = ${lineTotal} DH`});const msg=`Bonjour ${CONFIG.brand},\nNouvelle commande\nClient: ${n}\nTéléphone: ${ph}\nAdresse: ${ad}\n\nArticles:\n${lines.join('\n')}\n\nTotal: ${total} DH`;fetch(`${API.python}/orders`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer_name:n,customer_phone:ph,customer_address:ad,items:cart})}).catch(()=>{console.warn('Serveur Python/MySQL indisponible — commande envoyée quand même sur WhatsApp')});cart=[];localStorage.setItem('yourbrand_cart','[]');renderCartCount();renderCartPage();window.open(`https://wa.me/${CONFIG.whatsapp}?text=${encodeURIComponent(msg)}`,'_blank');showToast('Commande envoyée sur WhatsApp')}
function showToast(t){let x=$('#toast');if(!x){x=document.createElement('div');x.id='toast';x.className='toast';document.body.appendChild(x)}x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2200)}
function initSearch(){const b=$('#searchBtn'),p=$('#searchPanel'),i=$('#searchInput'),c=$('#clearSearch');if(!b||!p)return;b.onclick=()=>{p.classList.toggle('open');if(i)i.focus()};if(i)i.oninput=()=>{searchTerm=i.value;renderProducts()};if(c)c.onclick=()=>{i.value='';searchTerm='';renderProducts()}}
function initPage(){applyConfig();setActiveNav();initMobile();initSearch();renderCartCount();const filters=$$('.filter');filters.forEach(b=>b.onclick=()=>{filters.forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCategory=b.dataset.category;renderProducts()});const cm=$('#closeModal'),modal=$('#productModal');if(cm&&modal){cm.onclick=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')}}const cp=$('#checkoutBtnPage');if(cp)cp.onclick=checkout;const nf=$('#newsletterForm');if(nf)nf.onsubmit=async e=>{e.preventDefault();try{await fetch(`${API.python}/newsletter`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:$('#newsletterEmail').value})})}catch{}showToast('Merci ! Vous êtes inscrit(e).');nf.reset()};const cf=$('#contactForm');if(cf)cf.onsubmit=async e=>{e.preventDefault();const fd=new FormData(cf);try{await fetch(`${API.python}/contact`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(fd.entries()))});showToast('Message envoyé !');cf.reset()}catch{showToast('Le serveur est indisponible.')}}}
function initHero(){const wrap=$('#heroSlides');if(!wrap)return;const slides=[['Votre style, votre signature.','Ajoutez votre propre image principale et présentez votre collection.','Découvrir la collection'],['L’élégance au quotidien.','Votre texte promotionnel.','Voir les nouveautés'],['Une collection pensée pour vous.','Votre campagne du moment.','Shopper maintenant']];let idx=0;wrap.innerHTML=slides.map((s,i)=>`<article class="hero-slide ${i?'':'active'}"><div class="hero-image"><div class="hero-image-label">IMAGE HERO ${String(i+1).padStart(2,'0')}</div></div><div class="shade"></div><div class="hero-copy"><p class="eyebrow">NOUVELLE COLLECTION</p><h1>${s[0]}</h1><p>${s[1]}</p><a href="boutique.html" class="button button-light">${s[2]}</a></div></article>`).join('');const dots=$('#sliderDots');dots.innerHTML=slides.map((_,i)=>`<button class="${i?'':'active'}" data-slide="${i}"></button>`).join('');const go=n=>{idx=(n+slides.length)%slides.length;$$('.hero-slide').forEach((s,i)=>s.classList.toggle('active',i===idx));$$('#sliderDots button').forEach((d,i)=>d.classList.toggle('active',i===idx))};$('#prevSlide').onclick=()=>go(idx-1);$('#nextSlide').onclick=()=>go(idx+1);$$('#sliderDots button').forEach(d=>d.onclick=()=>go(+d.dataset.slide));setInterval(()=>go(idx+1),6000)}
window.addEventListener('DOMContentLoaded',async()=>{initPage();await loadProducts();renderProducts('#productGrid',false);renderProducts('#featuredProducts',true);renderCartPage();initHero()});